### ISSUE TITLE
What's up with the site (c4-cams.qwazwsx.xyz) being down?

### ISSUE THREAD

**Issue by Maxxls** [qwazwsx/c4-cams#69]
Is this dead?

**Comment by qwazwsx** [comment]
Thanks so much for your interest in the project! I previously was hosting the DB using Heroku's free Mlab tier but they discontinued that service and I haven't found the time to spin up another server. Eventually, I'll get around to it but I've been pretty busy lately so it might be a while :(

If you want to run the site locally in the meantime you should be able to run the following to get it up and running:

* download and set up MongoDB as well as NodeJS, then install dependencies with `npm i`

* run `node importList.js` to convert the list.txt (from https://github.com/turbo/c4) into a JSON file ready for import to MongoDB

* then you can use `mongoimport --db c4-cams --collection camera_list --drop --jsonArray --file list.json` to import the camera list (warning this will drop all data previously stored in the db)

* after that you should just be able to run `node index.js` to spin up the server and connect to it via `http://localhost:3000`


you may need to set a few env vars to specify what DB to connect to: 
* `MONGODB_URI` (default: mongodb://localhost:27017
* `PORT` (default 3000)
* `dbName` - **you will have to change this to match your mongo config**

I wrote this ages ago and the code is basically a giant mess, so no guarantees that these steps will work exactly. You might have to go digging around in the spaghetti to fix some stuff. Also: I'm pretty sure a commit I pushed ages ago broke everything so you may want to stick with an older version, specifically this: https://github.com/qwazwsx/c4-cams/tree/0985dad2b01af238983f73dd6eb8a8670cfb9a20

Again I apologize for how messy the code and repository is, I wrote all this when I was pretty new to JS and I had absolutely no idea what I was doing. *Eventually* 🤞 I'll get around to getting the server spun up and refactoring the spaghetti

Let me know if you have any questions!

-qwazwsx :)

**Comment by qwazwsx** [comment]
Okay, the new server has been spun up! The site should be available again. Let me know if you experience any issues. :-)
